questions.destroy_all

questions = ["What was the best part of the day?",
"When did I feel grateful today?",
"What made me smile today",
"What made me laugh out loud today?",
"Who helped me today?",
"Who was kind to me today?",
"What insight did I gain today?",
"What did I learn today?",
"How am I better today than I was yesterday?",
"What did I read or listen to today that added value to my life?",
"How did technology make my life easier today?",
"What activity did I most enjoy today?",
"What was the most delicious thing I ate today?",
"What did I enjoy listening to today?",
"What made me think, “That smells good!” today?",
"What was pleasant to the touch today?",
"What beauty did I see today?",
"What was one small victory I had today?",
"What simple pleasure did I enjoy today?",
"What act of kindness did I witness today?",
"What did I create today?",
"What skills did I use today?",
"What strengths did I apply today?",
"What weakness was I able to keep in check today?",
"How was I able to help others today?",
"How did I move an important goal forward today?",
"How was my body an ally today?",
"Who was I happy to meet with, chat with, or run into today?",
"What compliment did I receive today?",
"How did I feel appreciated today?",
"Who showed me affection today?",
"What positive emotions did I experience today?",
"What negative thoughts, beliefs, or emotions was I able to release today?",
"What opportunity presented itself today?",
"What obstacle did I overcome today?",
"What problem was I able to resolve today?",
"What negative was I able to turn into a positive today?",
"What’s the silver lining to something that went wrong today?",
"What made me feel hopeful today?",
"How did I show gumption today?",
"How was I awesome today?",
"What positive habits did I engage in today?",
"What negative habits was I able to avoid today?",
"When did I feel love today?",
"When was I at peace today?",
"What did I do today that was fun?",
"What was something playful I did today?",
"How did I show myself compassion today?",
"What positive things did I notice about my surroundings today?",
"What made me appreciate my city, state (province), or country today?",
"When did I feel a sense of abundance today?",
"How did I feel connected to others today?",
"What is one positive thing I can say about today’s weather?",
"What made me feel energized today?",
"What made me happy to be alive today?"]

questions.each do |question|
  Question.create!(
  content: question )
end

user1 = User.create(email: "a@a.")
